### ISSUE TITLE
Move to MIT licenes?

### ISSUE THREAD

**Issue by brandonkelly** [chapter-three/AppleNewsAPI#2]
Would you all be open to changing the license of this library from GPL to MIT? GPL is a little restrictive in that you can only use the software on other GPL-licensed software. We would love to use this in an Apple News integration for Craft CMS, but are hesitant to release the integration under GPL. (We do plan on releasing it under MIT though.)

**Comment by gguridi** [comment]
I can't see any problem :)

**Comment by brandonkelly** [comment]
@gguridi @tbfisher Thanks guys 👍
