### ISSUE TITLE
Please tag the latest commit

### ISSUE THREAD

**Issue by m4olivei** [chapter-three/AppleNewsAPI#25]
Hi there!

I'm wondering if you could tag the latest commit. Folks are running into [issues](https://www.drupal.org/project/applenews/issues/3112392#comment-13938792) requiring `dev-master` of this package as a dependency of [drupal/applenews](https://www.drupal.org/project/applenews).

Here is the diff between the most recent tag and the latest:

https://github.com/chapter-three/AppleNewsAPI/compare/0.3.9...master

Thanks!

**Comment by minnur** [comment]
0.3.10 released.
