### ISSUE TITLE
Document Version

### ISSUE THREAD

**Issue by ZeroBeeOne** [chapter-three/AppleNewsAPI#3]
Hey there,

First off - thanks very much for the work you've put into this class, it's awesome. I notice when creating sample documents using the document API, I get a warning from the Apple News Preview app, relating to the document version (0.10.13) being behind the current.

I haven't been able to find any properties you are lacking support for from 1.0 (at least, of the components I find myself using), would upping the document version property at this point be acceptable?

**Comment by minnur** [comment]
bumped the library to 1.2. We will add more components later. Currently APN is on 1.3
